eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-79287604.okta.com/oauth2/default
    audience: api://default
